version: 2

models:
  - name: cadastro
    columns:
      - name: id
        data_tests:
          - not_null
        description: teste do meu amigo giovanni
      - name: nome
        data_tests:
          - not_null

  - name: cadastro2
    columns:
      - name: id
        data_tests:
          - not_null
      - name: nome
        data_tests:
          - not_null

  - name: trusted_cadastro
    columns:
      - name: id
        data_tests:
          - not_null
      - name: nome
        data_tests:
          - not_null

  - name: trusted_cadastro2
    columns:
      - name: id
        data_tests:
          - not_null
        description: teste do meu amigo giovanni
      - name: nome
        data_tests:
          - not_null
