dbtpoc:
  outputs:
    dev:
      account: qwa07524.east-us-2.azure.snowflakecomputing.com
      database: SNOW_DBT_POSTGRE
      password: '@Test;02@02'
      role: ACCOUNTADMIN
      schema: TRUSTED
      threads: 1
      host: qwa07524.east-us-2.azure.snowflakecomputing.com
      type: snowflake
      user: pocdddbtapp
      warehouse: COMPUTE_WH

  target: dev
